<?php $title = "bio"; include("header.php");?>
        <div class="col-md-10 col-md-offset-1" id="content">
          <h1>bio <small>Matthew Roberts</small></h1>
          <hr>
          <div class="thumbnail pull-right text-right" id="bio-pic">
            <img src="img/matt3.jpg" alt="Matthew Roberts">
            <div class="caption">
              <p>Laikipia District, Rift Valley Province, Kenya</p>
            </div>
          </div>
          <p><strong>Matthew Roberts</strong> was born and raised in <a href="http://www.town.parrsboro.ns.ca"  onclick="window.open(this.href,'_blank');return false;">Parrsboro, NS</a>. He has a passion for technology and design, at the age of 13, he began to experiment with the HTML language and has developed his skill set and abilities over the course of time.</p>
					<p>Together with his childhood friend, <a href="http://www.malcolmm.cc" onclick="window.open(this.href,'_blank');return false;">Malcolm McCulloch</a>, he founded <a href="http://www.stikmen.ca"  onclick="window.open(this.href,'_blank');return false;">Stikmen Graphic Design</a> in 2005, an outlet for their creative energies and a way to showcase their expanding web design knowledge. The partnership has matured over time and is currently an officially registered partnership with a growing portfolio of web design clients.</p>
					<p><em>Matthew</em> began attending <a href="http://www.kes.ns.ca"  onclick="window.open(this.href,'_blank');return false;">King's-Edgehill School</a>, a private boarding school, for Grade 10 and on top of his interest in technology and web design, became involved with the theatre programme offering his help as an theatrical technician. Over the course of three years at KES, <em>Matthew</em> familiarized himself with the technical aspects of theatre, to the point where he was employed by the school as one of their technicians during his Grade 12 year. At KES, Matthew was involved in productions of <em>Snoopy</em>, <em>Once on this Island</em>, <em>High School Musical</em>, <em>Fiddler on the Roof</em>, <em>Iolanthe</em>, <em>Pirates of Penzance</em>, and <em>The Pajama Game</em>; as well as various other theatrical, and musical events.</p>
					<p>At KES, <em>Matthew</em> began to take more interest in computer hardware and scavenged an old desktop computer from Malcolm (really old, older than him with 36MB RAM and a 130mHz Intel processor) which he took apart and tinkered with, eventually installing <a href="http://www.ubuntu.com"  onclick="window.open(this.href,'_blank');return false;">Ubuntu Server Edition</a> on to its tiny hard drive and thus began his adventure into the wonderful world of Linux and computer networking.</p>
					<p>After completing his high school diploma at KES with honours, <em>Matthew</em> spent a year at <a href="http://www.stfx.ca"  onclick="window.open(this.href,'_blank');return false;">St. Francis Xavier University,</a> obtained his first year of a Bachelor of Information Systems (BIS) with Dean's List, honours placement before deciding that StFX and the BIS program wasn't quite right for him. He transfered to the <a href="http://www.uoguelph.ca"  onclick="window.open(this.href,'_blank');return false;">University of Guelph</a> and combined his interest in psychology with his passion of computer science in the Information Systems and Human Behaviour (Honours) major (ISHB). Retaining his interest in business from his year at StFX he is minoring in Economics.</p>
					<p>He spent a summer working in professional theatre at the <a href="http://www.shipscompany.com" onclick="window.open(this.href,'_blank');return false;">Ship's Company Theatre</a> in Parrsboro, Nova Scotia, as a theatre technician, putting his knowledge of theatre technology from high school to use in a professional capacity. At the Ship, Matthew was involved in productions of <em>The Net</em>, and <em>Fishing for Frank</em>; as well as various other theatrical, and musical events.</p>
					<p>At the University of Guelph, Matthew has spent his time working at <a href="http://www.uoguelph.ca/svc/" onclick="window.open(this.href,'_blank');return false;">Student Volunteer Connections of Guelph</a>, a student run volunteer centre, as their webmaster and IT manager; and at <a href="http://www.uoguelph.ca/~curtain/" onclick="window.open(this.href,'_blank');return false;">Curtain Call Productions</a> first as a technician, and now as a Technical Director. At CCP, Matthew has been involved in productions of <em>RENT</em>, <em>Jekyll &amp; Hyde</em>, and <em>Cabaret</em>.</p>
					<p><em>Matthew</em> has spent the past two summers in Saskatoon, Saskatchewan working in IT at the <a href="http://sk.lung.ca" onclick="window.open(this.href,'_blank');return false;">Lung Association of Saskatchewan</a> and is finishing his degree at the University of Guelph.</p>
					<?php include("footer.php");?>